[project]
name = "forecasting"
version = "0.1.0"
description = "Forecasting"
authors = ["Guillaume Lemaitre <guillaume@probabl.ai>", "Olivier Grisel <olivier@probabl.ai>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tasks]

[dependencies]
notebook = ">=7.4.3,<8"
jupyterlab = ">=4.4.3,<5"
jupytext = ">=1.17.2,<2"
scikit-learn = ">=1.7.0,<2"
polars = "==1.24.0" # same as latest compatible emscripten build
matplotlib-base = ">=3.10.3,<4"
pyarrow = ">=20.0.0,<21"
holidays = ">=0.75,<0.76"
pip = ">=25.1.1,<26"
ipyleaflet = ">=0.20.0,<0.21"
pandas = ">=2.3.0,<3"
mlforecast = ">=1.0.2,<2"
altair = ">=5.5.0,<6"
graphviz = ">=13.1.0,<14"
pydot = ">=4.0.1,<5"
u8darts = ">=0.36.0,<0.37"
setuptools = "<81"
plotly = ">=6.2.0,<7"

[pypi-dependencies]
skrub = { git = "https://github.com/skrub-data/skrub", rev = "771f3870a23438211faefb0e54132781256acc0a" }
openmeteo-requests = ">=1.5.0, <2"
requests-cache = ">=1.2.1, <2"
retry-requests = ">=2.0.0, <3"

[feature.dev.dependencies]
ipykernel = "*"

[feature.lint.dependencies]
ruff = "*"
black = "*"

[feature.doc.dependencies]
jupyter-book = "*"
jupyterlite = "*"
jupyterlite-pyodide-kernel = "*"
python-libarchive-c = "*"

[feature.doc.tasks]
convert-to-notebooks = { cmd = "jupytext --to notebook ./content/python_files/*.py && mkdir -p ./content/notebooks && mv ./content/python_files/*.ipynb ./content/notebooks" }
convert-to-executed-notebooks = { cmd = "jupytext --to notebook --execute ./content/python_files/*.py && mkdir -p ./content/notebooks && mv ./content/python_files/*.ipynb ./content/notebooks" }
build-book = { cmd = "jupyter-book build book", depends-on = ["convert-to-notebooks"] }
build-jupyterlite = { cmd = "jupyter lite build --contents content --output-dir dist", cwd = "jupyterlite", depends-on = ["convert-to-notebooks"] }
serve-jupyterlite = { cmd = "python -m http.server", cwd = "jupyterlite/dist", depends-on = ["build-jupyterlite"] }

[environments]
lint = ["lint"]
doc = ["doc"]
dev = ["dev", "doc", "lint"]
