name: 'publish_book'
on:
  push:
    branches:
      - "main"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-gh-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: prefix-dev/setup-pixi@v0.8.10
        with:
          pixi-version: v0.48.2
          environments: doc
          
      - name: Convert Python file to notebooks for JupyterLite
        run: |
          # to create the predictions and validation curves cache
          pixi run -e doc convert-to-executed-notebooks
          # to clean the output
          pixi run -e doc convert-to-notebooks
          
      - name: Build the JupyterLite site
        run: |
          pixi run -e doc build-jupyterlite
          
      - name: Build and publish the book
        run: pixi run -e doc build-book
        
      - name: Copy jupyterlite site under the book directory
        run: |
          cp -r jupyterlite/dist book/_build/html/jupyterlite
          
      - name: Build slides
        run: pixi run -e doc build-slides
        
      - name: Copy slides under the book directory
        run: |
          cp -r content/slides/_site book/_build/html/slides
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./book/_build/html
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
