name: 'test'

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - '*'

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        environment: [default]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.2
        with:
          pixi-version: v0.41.1
          environments: ${{ matrix.environment }}

      - name: Run tests
        run: |
            pixi run generate-predictions
            pixi run -e doc convert-to-executed-notebooks

      - name: Test if we can build the documentation
        if: matrix.os == 'ubuntu-latest'
        run: pixi run -e doc build-book
